"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _quick_note_tab from './quick-note-tab.bones.json'
import _weekly_summary from './weekly-summary.bones.json'

configureBoneyard({"color":"#e8e6dc","darkColor":"#3d3d3a","animate":"shimmer","shimmerColor":"#f0eee6","darkShimmerColor":"#4d4c48","speed":"2s","shimmerAngle":110,"stagger":true,"transition":280})

registerBones({
  "quick-note-tab": _quick_note_tab,
  "weekly-summary": _weekly_summary,
})
